name: Publish Docker image

on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push image to Docker Hub
    runs-on: ubuntu-20.04
    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # TODO: figure out a smarter way to tag these rather than hard-coding version tags
      -
        name: Build and push arm
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms:  linux/arm64
          build-args: |-
            GO_ARCH=arm64
            GO_VERSION=1.17.7
          file: ./Dockerfile
          pull: true
          push: true
          cache-from: type=registry,ref=camerondurham/unofficial-al2-golang:latest
          cache-to: type=inline
          tags: camerondurham/unofficial-al2-golang:1.17.7-arm64
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      -
        name: Build and push x86
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms:  linux/amd64
          build-args: |-
            GO_ARCH=amd64
            GO_VERSION=1.17.7
          file: ./Dockerfile
          pull: true
          push: true
          cache-from: type=registry,ref=camerondurham/unofficial-al2-golang:latest
          cache-to: type=inline
          tags: camerondurham/unofficial-al2-golang:1.17.7-amd64
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

